name: icu_parser
description: An extraction of icu parser from the intl_translation package
version: 1.5.0
homepage: https://github.com/sysint64/icu_parser.git

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  petitparser: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.19.0
