name: icu_parser
description: An extraction of icu parser from the intl_translation package
version: 0.17.10+1
homepage: https://github.com/sysint64/icu_parser.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.12 <0.40.0'
  petitparser: ^3.0.0

dev_dependencies:
