name: icu_parser
description: An extraction of icu parser from the intl_translation package
version: 1.0.0
homepage: https://github.com/sysint64/icu_parser.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  petitparser: ^4.0.2

dev_dependencies:
